### ISSUE TITLE
YAT (Yet Another Test)

### ISSUE THREAD

**Issue by hbushouse** [eslavich/jirahub-sandbox-ii#18]
This time going the GitHub -> Jira direction.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1399](https://jira-test.stsci.edu/browse/JP-1399)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira-test.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira-test.stsci.edu/browse/JP-1399?focusedCommentId=456677#comment-456677):_

Hmmm, the Jira ticket type got set to "Story". Not sure that's the best default to use. I think the generic "Task" would be better.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira-test.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira-test.stsci.edu/browse/JP-1399?focusedCommentId=456678#comment-456678):_

[Edward Slavich](https://jira-test.stsci.edu/secure/ViewProfile.jspa?name=eslavich) I suggest setting the default ticket type to "Task" when the bot creates a Jira ticket from a new GitHub issue. Otherwise everything seems to be working well!
